# fly.toml app configuration file generated for rocket-seat-node-js-api on 2025-08-14T23:55:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rocket-seat-node-js-api'
primary_region = 'gru'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "/usr/local/bin/npm run run db:migrate"