GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/373ddee2-ebc3-41d4-8fac-dabd8c4e14cc

###

POST http://localhost:3000/courses
Content-Type: application/json

{
  "title": "javaScript",
  "description": "Curso de javaScript"
}

###

PUT http://localhost:3000/courses/:id

###

PATCH http://localhost:3000/courses/:id

###

DELETE http://localhost:3000/courses/:id