GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/661ee891-99bd-4d60-a192-0bfc290d7e4c

###

POST http://localhost:3000/courses
Content-Type: application/json

{
  "title": "Docker",
  "description": "Curso de docker"
}

###

PUT http://localhost:3000/courses/:id

###

PATCH http://localhost:3000/courses/:id

###

DELETE http://localhost:3000/courses/:id